/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-09 02:43:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BoardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1596941029779L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1596937694342L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\"\r\n");
      out.write("        integrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main_style.css\" />\r\n");
      out.write("    <title>AD STORY</title>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"all-of-div\">\r\n");
      out.write("        <div class=\"main-container\">\r\n");
      out.write("            <div class=\"menu-icon\">\r\n");
      out.write("                <i class=\"fas fa-bars header__menu\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <header class=\"header\">\r\n");
      out.write("                <div class=\"logout-div\">\r\n");
      out.write("                    <button\r\n");
      out.write("                        class=\"float-right bg-transparent hover:bg-blue-500 text-gray-700 font-semibold hover:text-white py-2 px-4 border border-gray-700 hover:border-transparent rounded\">\r\n");
      out.write("                        로그아웃\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <aside class=\"sidenav\">\r\n");
      out.write("                <div class=\"sidenav__close-icon\">\r\n");
      out.write("                    <i class=\"fas fa-times sidenav__brand-close\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"LOGO\">\r\n");
      out.write("                    <b>AD STORY</b>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"profile_img_div\">\r\n");
      out.write("                    <img class=\"profile_img\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/profile.png\" alt=\"프로필사진\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                    회원아이디\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"sidenav__list\">\r\n");
      out.write("                    <li class=\"sidenav__list-item\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/';\">홈</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/view';\">게시판</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\">마이페이지</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\">회사소개</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\">광고하기</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\">포인트랭킹</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\">문의게시판</li>\r\n");
      out.write("                    <li class=\"sidenav__list-item\">공지사항</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <main class=\"main\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <nav class=\"category-menu sm:flex sm:justify-center sm:items-center mt-4\">\r\n");
      out.write("                    <div class=\"flex flex-col sm:flex-row\">\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">전체</a>\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">건강식품</a>\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">화장품&미용</a>\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">가전제품</a>\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">생활용품</a>\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">교육</a>\r\n");
      out.write("                        <a class=\"mt-3 text-gray-600 hover:underline sm:mx-3 sm:mt-0\" href=\"#\">요식업</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"article-container mobile-display-block\">\r\n");
      out.write("                    <img class='article-img mobile-hide' src=\"");
      out.print(request.getContextPath() );
      out.write("/images/test_img.jpg\" alt=\"홍보 사진\">\r\n");
      out.write("                    <div class=\"article-content mobile-text-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            건강식품 | 제주오렌지\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-2xl\">\r\n");
      out.write("                            오렌지 쇼핑몰 홍보\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 잔여 마일리지 : 1,000,000P </div>\r\n");
      out.write("                        <div> 단가 : 500P</div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 참여인원 : 5명 </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"done article-container mobile-display-block\">\r\n");
      out.write("                    <img class='article-img mobile-hide' src=\"");
      out.print(request.getContextPath() );
      out.write("/images/puppy.png\" alt=\"홍보 사진\">\r\n");
      out.write("                    <div class=\"article-content mobile-text-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            교육 | 강아지전문학원\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-2xl\">\r\n");
      out.write("                            훈련 학원 웹페이지 홍보\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div> </div>\r\n");
      out.write("                        <div> 잔여 마일리지 : 0P </div>\r\n");
      out.write("                        <div> 단가 : 200P</div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 참여인원 : 125명 </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"done-check-wapper\">\r\n");
      out.write("                        <div class=\"done-check-content\">\r\n");
      out.write("                            <div class=\"done-check-content-align text-4xl\">마감</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"article-container mobile-display-block\">\r\n");
      out.write("                    <img class='article-img mobile-hide' src=\"");
      out.print(request.getContextPath() );
      out.write("/images/test_img.jpg\" alt=\"홍보 사진\">\r\n");
      out.write("                    <div class=\"article-content mobile-text-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            건강식품 | 제주오렌지\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-2xl\">\r\n");
      out.write("                            오렌지 상품홍보\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 잔여 마일리지 : 1,000,000P </div>\r\n");
      out.write("                        <div> 단가 : 500P</div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 참여인원 : 5명 </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"article-container mobile-display-block\">\r\n");
      out.write("                    <img class='article-img mobile-hide' src=\"");
      out.print(request.getContextPath() );
      out.write("/images/test_img.jpg\" alt=\"홍보 사진\">\r\n");
      out.write("                    <div class=\"article-content mobile-text-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            건강식품 | 제주오렌지\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-2xl\">\r\n");
      out.write("                            오렌지 상품홍보\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 잔여 마일리지 : 1,000,000P </div>\r\n");
      out.write("                        <div> 단가 : 500P</div>\r\n");
      out.write("                        <div>　</div>\r\n");
      out.write("                        <div> 참여인원 : 5명 </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"search-bar-div\">\r\n");
      out.write("                    <div class=\"search-bar relative text-lg bg-transparent text-gray-800\">\r\n");
      out.write("                        <div class=\"flex items-center border-b border-b-2 border-gray-500 py-2\">\r\n");
      out.write("                            <input class=\"bg-transparent border-none mr-3 px-2 leading-tight focus:outline-none\"\r\n");
      out.write("                                type=\"text\" placeholder=\"검색\">\r\n");
      out.write("                            <button type=\"submit\" class=\"absolute right-0 top-0 mt-3 mr-4\">\r\n");
      out.write("                                <svg class=\"h-4 w-4 fill-current\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                    xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" id=\"Capa_1\" x=\"0px\" y=\"0px\"\r\n");
      out.write("                                    viewBox=\"0 0 56.966 56.966\" style=\"enable-background:new 0 0 56.966 56.966;\"\r\n");
      out.write("                                    xml:space=\"preserve\" width=\"512px\" height=\"512px\">\r\n");
      out.write("                                    <path\r\n");
      out.write("                                        d=\"M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"align-middle flex justify-center\">\r\n");
      out.write("                        <div class=\"flex rounded-md mt-8\">\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                                class=\"py-2 px-4 leading-tight bg-white border border-gray-500 text-gray-700 border-r-0 ml-0 rounded-l hover:bg-blue-500 hover:text-white\"><span>이전</a></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                                class=\"py-2 px-4 leading-tight bg-white border border-gray-500 text-gray-700 border-r-0 hover:bg-blue-500 hover:text-white\"><span>1</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                                class=\"py-2 px-4 leading-tight bg-white border border-gray-500 text-gray-700 border-r-0 hover:bg-blue-500 hover:text-white\"><span>2</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                                class=\"py-2 px-4 leading-tight bg-white border border-gray-500 text-gray-700 border-r-0 hover:bg-blue-500 hover:text-white\"><span>3</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                                class=\"py-2 px-4 leading-tight bg-white border border-gray-500 text-gray-700 rounded-r hover:bg-blue-500 hover:text-white\"><span>다음</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bottom-of-main\"></div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </main>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
